FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app

# Azure App Service expects the container to listen on WEBSITES_PORT (we set 8501)
EXPOSE 8501

CMD ["bash","-lc","streamlit run app/ui/streamlit_app.py --server.address 0.0.0.0 --server.port ${PORT:-8501}"]
